name = "server"
type = "javascript"
account_id = "aee97446afa4e01297e84715bd34f1ea"
workers_dev = true
compatibility_date = "2025-03-24"

[site]
bucket = "./dist" # Specify the directory containing your built files
entry-point = "./" # Optional, defaults to "./"
