name = "try"
type = "javascript"
account_id = "aee97446afa4e01297e84715bd34f1ea"
workers_dev = true
compatibility_date = "2025-03-24"

[site]
bucket = "./dist"  # This must match the output directory from your build process
entry-point = "./src"

[build]
command = "npm run build"

[env]
pages_build_output_dir = "./login.html"  # Specifies the build output directory

